<?php

/**
 * Add a form submission data as a new row in the database
 *  - AFTER validation
 *
 *
 * @param [array] $validated_POST_data
 * @return void
 */
function tli_add_form_to_db( $validated_POST_data ) {

  // format data for MySQL columns
  $data = array(
    'first_name'     => $validated_POST_data['firstName'],
    'middle_name'    => $validated_POST_data['middleName'],
    'last_name'      => $validated_POST_data['lastName'],
    'phone'          => $validated_POST_data['phone'],
    'email'          => $validated_POST_data['email'],
    'date_of_birth'  => $validated_POST_data['birthdate'],
    'job_position'   => $validated_POST_data['jobPosition'],
    'date_available' => $validated_POST_data['dateAvailable'],
    'legal_to_work'  => $validated_POST_data['legal'],
    'current_street'   => $validated_POST_data['currentStreet'],
    'current_city'     => $validated_POST_data['currentCity'],
    'current_state'    => $validated_POST_data['currentState'],
    'current_zipcode'  => $validated_POST_data['currentZipcode'],
    'current_duration' => $validated_POST_data['currentDuration'],
    'mailing_street'   => $validated_POST_data['mailingStreet'],
    'mailing_city'     => $validated_POST_data['mailingCity'],
    'mailing_state'    => $validated_POST_data['mailingState'],
    'mailing_zipcode'  => $validated_POST_data['mailingZipcode'],
    'mailing_duration' => $validated_POST_data['mailingDuration'],
    'prev1_street'     => $validated_POST_data['prev1Street'],
    'prev1_city'       => $validated_POST_data['prev1City'],
    'prev1_state'      => $validated_POST_data['prev1State'],
    'prev1_zipcode'    => $validated_POST_data['prev1Zipcode'],
    'prev1_duration'   => $validated_POST_data['prev1Duration'],
    'prev2_street'     => $validated_POST_data['prev2Street'],
    'prev2_city'       => $validated_POST_data['prev2City'],
    'prev2_state'      => $validated_POST_data['prev2State'],
    'prev2_zipcode'    => $validated_POST_data['prev2Zipcode'],
    'prev2_duration'   => $validated_POST_data['prev2Duration'],
    'prev3_street'     => $validated_POST_data['prev3Street'],
    'prev3_city'       => $validated_POST_data['prev3City'],
    'prev3_state'      => $validated_POST_data['prev3State'],
    'prev3_zipcode'    => $validated_POST_data['prev3Zipcode'],
    'prev3_duration'   => $validated_POST_data['prev3Duration'],
    'current_license_state'        => $validated_POST_data['currentLicenseState'],
    'current_license_number'       => $validated_POST_data['currentLicenseNumber'],
    'current_license_type'         => $validated_POST_data['currentLicenseType'],
    'current_license_endorsements' => $validated_POST_data['currentLicenseEndorsements'],
    'current_license_exp_date'     => $validated_POST_data['currentLicenseExpDate'],
    'prev1_license_state'          => $validated_POST_data['prev1LicenseState'],
    'prev1_license_number'         => $validated_POST_data['prev1LicenseNumber'],
    'prev1_license_type'           => $validated_POST_data['prev1LicenseType'],
    'prev1_license_endorsements'   => $validated_POST_data['prev1LicenseEndorsements'],
    'prev1_license_exp_date'       => $validated_POST_data['prev1LicenseExpDate'],
    'prev2_license_state'          => $validated_POST_data['prev2LicenseState'],
    'prev2_license_number'         => $validated_POST_data['prev2LicenseNumber'],
    'prev2_license_type'           => $validated_POST_data['prev2LicenseType'],
    'prev2_license_endorsements'   => $validated_POST_data['prev2LicenseEndorsements'],
    'prev2_license_exp_date'       => $validated_POST_data['prev2LicenseExpDate'],
    'straight_truck_type'        => $validated_POST_data['straightTruckType'],
    'straight_truck_date_from'   => $validated_POST_data['straightTruckDateFrom'],
    'straight_truck_date_to'     => $validated_POST_data['straightTruckDateTo'],
    'straight_truck_miles'       => $validated_POST_data['straightTruckMiles'],
    'tractor_semi_type'          => $validated_POST_data['tractorSemiType'],
    'tractor_semi_date_from'     => $validated_POST_data['tractorSemiDateFrom'],
    'tractor_semi_date_to'       => $validated_POST_data['tractorSemiDateTo'],
    'tractor_semi_miles'         => $validated_POST_data['tractorSemiMiles'],
    'tractor_trailers_type'      => $validated_POST_data['tractorTrailersType'],
    'tractor_trailers_date_from' => $validated_POST_data['tractorTrailersDateFrom'],
    'tractor_trailers_date_to'   => $validated_POST_data['tractorTrailersDateTo'],
    'tractor_trailers_miles'     => $validated_POST_data['tractorTrailersMiles'],
    'tractor_tanker_type'        => $validated_POST_data['tractorTankerType'],
    'tractor_tanker_date_from'   => $validated_POST_data['tractorTankerDateFrom'],
    'tractor_tanker_date_to'     => $validated_POST_data['tractorTankerDateTo'],
    'tractor_tanker_miles'       => $validated_POST_data['tractorTankerMiles'],
    'other_type'                 => $validated_POST_data['otherType'],
    'other_date_from'            => $validated_POST_data['otherDateFrom'],
    'other_date_to'              => $validated_POST_data['otherDateTo'],
    'other_miles'                => $validated_POST_data['otherMiles'],
    'accident1_date'        => $validated_POST_data['accident1Date'],
    'accident1_description' => $validated_POST_data['accident1Description'],
    'accident1_fatalities'  => $validated_POST_data['accident1Fatalities'],
    'accident1_injuries'    => $validated_POST_data['accident1Injuries'],
    'accident1_spill'       => $validated_POST_data['accident1Spill'],
    'accident2_date'        => $validated_POST_data['accident2Date'],
    'accident2_description' => $validated_POST_data['accident2Description'],
    'accident2_fatalities'  => $validated_POST_data['accident2Fatalities'],
    'accident2_injuries'    => $validated_POST_data['accident2Injuries'],
    'accident2_spill'       => $validated_POST_data['accident2Spill'],
    'accident3_date'        => $validated_POST_data['accident3Date'],
    'accident3_description' => $validated_POST_data['accident3Description'],
    'accident3_fatalities'  => $validated_POST_data['accident3Fatalities'],
    'accident3_injuries'    => $validated_POST_data['accident3Injuries'],
    'accident3_spill'       => $validated_POST_data['accident3Spill'],
    'conviction1_date'        => $validated_POST_data['conviction1Date'],
    'conviction1_description' => $validated_POST_data['conviction1Description'],
    'conviction1_state'       => $validated_POST_data['conviction1State'],
    'conviction1_penalty'     => $validated_POST_data['conviction1Penalty'],
    'conviction2_date'        => $validated_POST_data['conviction2Date'],
    'conviction2_description' => $validated_POST_data['conviction2Description'],
    'conviction2_state'       => $validated_POST_data['conviction2State'],
    'conviction2_penalty'     => $validated_POST_data['conviction2Penalty'],
    'conviction3_date'        => $validated_POST_data['conviction3Date'],
    'conviction3_description' => $validated_POST_data['conviction3Description'],
    'conviction3_state'       => $validated_POST_data['conviction3State'],
    'conviction3_penalty'     => $validated_POST_data['conviction3Penalty'],
    'denied_license'          => $validated_POST_data['deniedLicense'],
    'suspended_license'       => $validated_POST_data['suspendedLicense'],
    'current_employer_name'      => $validated_POST_data['currentEmployerName'],
    'current_employer_phone'     => $validated_POST_data['currentEmployerPhone'],
    'current_employer_address'   => $validated_POST_data['currentEmployerAddress'],
    'current_employer_position'  => $validated_POST_data['currentEmployerPositionHeld'],
    'current_employer_date_from' => $validated_POST_data['currentEmployerDateFrom'],
    'current_employer_date_to'   => $validated_POST_data['currentEmployerDateTo'],
    'current_employer_reason'    => $validated_POST_data['currentEmployerReasonForLeaving'],
    'current_employer_salary'    => $validated_POST_data['currentEmployerSalary'],
    'current_employer_gaps'      => $validated_POST_data['currentEmployerGaps'],
    'current_employer_safety'    => $validated_POST_data['currentEmployerSafetyRegulations'],
    'current_employer_dot'       => $validated_POST_data['currentEmployerDoT'],
    'prev1_employer_name'        => $validated_POST_data['prev1EmployerName'],
    'prev1_employer_phone'       => $validated_POST_data['prev1EmployerPhone'],
    'prev1_employer_address'     => $validated_POST_data['prev1EmployerAddress'],
    'prev1_employer_position'    => $validated_POST_data['prev1EmployerPositionHeld'],
    'prev1_employer_date_from'   => $validated_POST_data['prev1EmployerDateFrom'],
    'prev1_employer_date_to'     => $validated_POST_data['prev1EmployerDateTo'],
    'prev1_employer_reason'      => $validated_POST_data['prev1EmployerReasonForLeaving'],
    'prev1_employer_salary'      => $validated_POST_data['prev1EmployerSalary'],
    'prev1_employer_gaps'        => $validated_POST_data['prev1EmployerGaps'],
    'prev1_employer_safety'      => $validated_POST_data['prev1EmployerSafetyRegulations'],
    'prev1_employer_dot'         => $validated_POST_data['prev1EmployerDoT'],
    'prev2_employer_name'        => $validated_POST_data['prev2EmployerName'],
    'prev2_employer_phone'       => $validated_POST_data['prev2EmployerPhone'],
    'prev2_employer_address'     => $validated_POST_data['prev2EmployerAddress'],
    'prev2_employer_position'    => $validated_POST_data['prev2EmployerPositionHeld'],
    'prev2_employer_date_from'   => $validated_POST_data['prev2EmployerDateFrom'],
    'prev2_employer_date_to'     => $validated_POST_data['prev2EmployerDateTo'],
    'prev2_employer_reason'      => $validated_POST_data['prev2EmployerReasonForLeaving'],
    'prev2_employer_salary'      => $validated_POST_data['prev2EmployerSalary'],
    'prev2_employer_gaps'        => $validated_POST_data['prev2EmployerGaps'],
    'prev2_employer_safety'      => $validated_POST_data['prev2EmployerSafetyRegulations'],
    'prev2_employer_dot'         => $validated_POST_data['prev2EmployerDoT'],
    'edu_hs_name_location'        => $validated_POST_data['hsNameLocation'],
    'edu_hs_course_study'         => $validated_POST_data['hsCourseStudy'],
    'edu_hs_years_completed'      => $validated_POST_data['hsYearsCompleted'],
    'edu_hs_graduated'            => $validated_POST_data['hsGraduated'],
    'edu_hs_details'              => $validated_POST_data['hsDetails'],
    'edu_college_name_location'   => $validated_POST_data['collegeNameLocation'],
    'edu_college_course_study'    => $validated_POST_data['collegeCourseStudy'],
    'edu_college_years_completed' => $validated_POST_data['collegeYearsCompleted'],
    'edu_college_graduated'       => $validated_POST_data['collegeGraduated'],
    'edu_college_details'         => $validated_POST_data['collegeDetails'],
    'edu_other_name_location'     => $validated_POST_data['otherNameLocation'],
    'edu_other_course_study'      => $validated_POST_data['otherCourseStudy'],
    'edu_other_years_completed'   => $validated_POST_data['otherYearsCompleted'],
    'edu_other_graduated'         => $validated_POST_data['otherGraduated'],
    'edu_other_details'           => $validated_POST_data['otherDetails'],
    'applicant_name_printed'   => $validated_POST_data['applicantNamePrinted'],
    'applicant_signature_date' => $validated_POST_data['applicantSignatureDate'],
    'applicant_signature'      => $validated_POST_data['applicantSignature'],
  );

  global $wpdb;
  $wpdb->show_errors();

  $tablename = $wpdb->prefix.'tli_form_submissions';

  $wpdb->insert( $tablename, $data );
  //$wpdb->print_error();
}


/**
 * Create the database table to store Job Application form submissions
 *
 * @return void
 */
function tli_create_table() {
  global $wpdb;
  $charset_collate = $wpdb->get_charset_collate();
  require_once( ABSPATH . 'wp-admin/includes/upgrade.php' );

  $table_name = $wpdb->prefix . 'tli_form_submissions';
  $sql = "CREATE TABLE $table_name (
    app_id INTEGER NOT NULL AUTO_INCREMENT,
  /* Applicant Info */
    first_name     VARCHAR(50)  NOT NULL,
    middle_name    VARCHAR(50)  NOT NULL,
    last_name      VARCHAR(50)  NOT NULL,
    phone          VARCHAR(15)  NOT NULL,
    email          VARCHAR(255) NOT NULL,
    date_of_birth  DATE         NOT NULL,
    job_position   VARCHAR(255) NOT NULL,
    date_available DATE         NOT NULL,
    legal_to_work  VARCHAR(3)   NOT NULL,
  /* Current Address */
    current_street   VARCHAR(255) NOT NULL,
    current_city     VARCHAR(100) NOT NULL,
    current_state    VARCHAR(2)   NOT NULL,
    current_zipcode  VARCHAR(5)   NOT NULL,
    current_duration VARCHAR(255) NOT NULL,
  /* Mailing Address */
    mailing_street   VARCHAR(255) NOT NULL,
    mailing_city     VARCHAR(100) NOT NULL,
    mailing_state    VARCHAR(2)   NOT NULL,
    mailing_zipcode  VARCHAR(5)   NOT NULL,
    mailing_duration VARCHAR(255) NOT NULL,
  /* Previous Address 1 */
    prev1_street   VARCHAR(255) NULL,
    prev1_city     VARCHAR(100) NULL,
    prev1_state    VARCHAR(2)   NULL,
    prev1_zipcode  VARCHAR(5)   NULL,
    prev1_duration VARCHAR(255) NULL,
  /* Previous Address 2 */
    prev2_street   VARCHAR(255) NULL,
    prev2_city     VARCHAR(100) NULL,
    prev2_state    VARCHAR(2)   NULL,
    prev2_zipcode  VARCHAR(5)   NULL,
    prev2_duration VARCHAR(255) NULL,
  /* Previous Address 3 */
    prev3_street   VARCHAR(255) NULL,
    prev3_city     VARCHAR(100) NULL,
    prev3_state    VARCHAR(2)   NULL,
    prev3_zipcode  VARCHAR(5)   NULL,
    prev3_duration VARCHAR(255) NULL,
  /* Current License */
    current_license_state        VARCHAR(2)   NOT NULL,
    current_license_number       VARCHAR(20)  NOT NULL,
    current_license_type         VARCHAR(50)  NOT NULL,
    current_license_endorsements VARCHAR(255) NOT NULL,
    current_license_exp_date     DATE         NOT NULL,
  /* Previous License 1 */
    prev1_license_state          VARCHAR(2)   NULL,
    prev1_license_number         VARCHAR(20)  NULL,
    prev1_license_type           VARCHAR(50)  NULL,
    prev1_license_endorsements   VARCHAR(255) NULL,
    prev1_license_exp_date       DATE         NULL,
  /* Previous License 2 */
    prev2_license_state          VARCHAR(2)   NULL,
    prev2_license_number         VARCHAR(20)  NULL,
    prev2_license_type           VARCHAR(50)  NULL,
    prev2_license_endorsements   VARCHAR(255) NULL,
    prev2_license_exp_date       DATE         NULL,
  /* Straight Truck - Driving Experience */
    straight_truck_type        TEXT         NULL,
    straight_truck_date_from   DATE         NULL,
    straight_truck_date_to     DATE         NULL,
    straight_truck_miles       VARCHAR(50)  NULL,
  /* Tractor Semi-Trailer - Driving Experience */
    tractor_semi_type          TEXT         NULL,
    tractor_semi_date_from     DATE         NULL,
    tractor_semi_date_to       DATE         NULL,
    tractor_semi_miles         VARCHAR(50)  NULL,
  /* Tractor 2 Trailers - Driving Experience */
    tractor_trailers_type      TEXT         NULL,
    tractor_trailers_date_from DATE         NULL,
    tractor_trailers_date_to   DATE         NULL,
    tractor_trailers_miles     VARCHAR(50)  NULL,
  /* Tractor Tanker - Driving Experience */
    tractor_tanker_type        TEXT         NULL,
    tractor_tanker_date_from   DATE         NULL,
    tractor_tanker_date_to     DATE         NULL,
    tractor_tanker_miles       VARCHAR(50)  NULL,
  /* Other - Driving Experience */
    other_type                 VARCHAR(255) NULL,
    other_date_from            DATE         NULL,
    other_date_to              DATE         NULL,
    other_miles                VARCHAR(50)  NULL,
  /* Accident 1 */
    accident1_date        DATE       NULL,
    accident1_description TEXT       NULL,
    accident1_fatalities  TINYINT(3) NULL,
    accident1_injuries    TINYINT(3) NULL,
    accident1_spill       VARCHAR(3) NULL,
  /* Accident 2 */
    accident2_date        DATE       NULL,
    accident2_description TEXT       NULL,
    accident2_fatalities  TINYINT(3) NULL,
    accident2_injuries    TINYINT(3) NULL,
    accident2_spill       VARCHAR(3) NULL,
  /* Accident 3 */
    accident3_date        DATE       NULL,
    accident3_description TEXT       NULL,
    accident3_fatalities  TINYINT(3) NULL,
    accident3_injuries    TINYINT(3) NULL,
    accident3_spill       VARCHAR(3) NULL,
  /* Conviction 1 */
    conviction1_date        DATE         NULL,
    conviction1_description TEXT         NULL,
    conviction1_state       VARCHAR(2)   NULL,
    conviction1_penalty     VARCHAR(255) NULL,
  /* Conviction 2 */
    conviction2_date        DATE         NULL,
    conviction2_description TEXT         NULL,
    conviction2_state       VARCHAR(2)   NULL,
    conviction2_penalty     VARCHAR(255) NULL,
  /* Conviction 3 */
    conviction3_date        DATE         NULL,
    conviction3_description TEXT         NULL,
    conviction3_state       VARCHAR(2)   NULL,
    conviction3_penalty     VARCHAR(255) NULL,
  /* Denied or Suspended License */
    denied_license          VARCHAR(3)   NOT NULL,
    suspended_license       VARCHAR(3)   NOT NULL,
  /* Current Employer */
    current_employer_name      VARCHAR(100) NULL,
    current_employer_phone     VARCHAR(15)  NULL,
    current_employer_address   VARCHAR(255) NULL,
    current_employer_position  VARCHAR(255) NULL,
    current_employer_date_from DATE         NULL,
    current_employer_date_to   DATE         NULL,
    current_employer_reason    VARCHAR(255) NULL,
    current_employer_salary    VARCHAR(255) NULL,
    current_employer_gaps      TEXT         NULL,
    current_employer_safety    VARCHAR(3)   NULL,
    current_employer_dot       VARCHAR(3)   NULL,
  /* Previous Employer 1 */
    prev1_employer_name        VARCHAR(100) NULL,
    prev1_employer_phone       VARCHAR(15)  NULL,
    prev1_employer_address     VARCHAR(255) NULL,
    prev1_employer_position    VARCHAR(255) NULL,
    prev1_employer_date_from   DATE         NULL,
    prev1_employer_date_to     DATE         NULL,
    prev1_employer_reason      VARCHAR(255) NULL,
    prev1_employer_salary      VARCHAR(255) NULL,
    prev1_employer_gaps        TEXT         NULL,
    prev1_employer_safety      VARCHAR(3)   NULL,
    prev1_employer_dot         VARCHAR(3)   NULL,
  /* Previous Employer 2 */
    prev2_employer_name        VARCHAR(100) NULL,
    prev2_employer_phone       VARCHAR(15)  NULL,
    prev2_employer_address     VARCHAR(255) NULL,
    prev2_employer_position    VARCHAR(255) NULL,
    prev2_employer_date_from   DATE         NULL,
    prev2_employer_date_to     DATE         NULL,
    prev2_employer_reason      VARCHAR(255) NULL,
    prev2_employer_salary      VARCHAR(255) NULL,
    prev2_employer_gaps        TEXT         NULL,
    prev2_employer_safety      VARCHAR(3)   NULL,
    prev2_employer_dot         VARCHAR(3)   NULL,
  /* High School */
    edu_hs_name_location        VARCHAR(100) NULL,
    edu_hs_course_study         VARCHAR(255) NULL,
    edu_hs_years_completed      TINYINT(1)   NULL,
    edu_hs_graduated            VARCHAR(3)   NULL,
    edu_hs_details              VARCHAR(255) NULL,
  /* College */
    edu_college_name_location   VARCHAR(100) NULL,
    edu_college_course_study    VARCHAR(255) NULL,
    edu_college_years_completed TINYINT(1)   NULL,
    edu_college_graduated       VARCHAR(3)   NULL,
    edu_college_details         VARCHAR(255) NULL,
  /* Other */
    edu_other_name_location     VARCHAR(100) NULL,
    edu_other_course_study      VARCHAR(255) NULL,
    edu_other_years_completed   TINYINT(1)   NULL,
    edu_other_graduated         VARCHAR(3)   NULL,
    edu_other_details           VARCHAR(255) NULL,
  /* Sign */
    applicant_name_printed   VARCHAR(100)  NOT NULL,
    applicant_signature_date DATE          NOT NULL,
    applicant_signature      VARCHAR(100)  NOT NULL,
    PRIMARY KEY (app_id)
  ) $charset_collate;";
  dbDelta( $sql );

}